---
title: "lab3A_jelia"
author: "James Elia"
date: "9/7/2020"
bibliography: C:/Users/eliaj/OneDrive/Documents/UMass/references.bib
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Lab 3A

```{r, eval=FALSE}
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "C:/Users/eliaj/OneDrive/Documents/UMass/portal_data_joined.csv")
```

### Challenge 1
```{r}
surveys <- read.csv("C:/Users/eliaj/OneDrive/Documents/UMass/portal_data_joined.csv")

head(surveys)

View(surveys)

str(surveys)

```

"Data frame" class
34786 rows, 13 columns
48 species

###Challenge 2
```{r}
surveys_200 <- surveys[200, ]
n_rows <- nrow(surveys)
surveys_last <- surveys[n_rows, ]
surveys_middle <- surveys[n_rows / 2, ]
surveys_head <- surveys[-(7:n_rows), ]
```

###Challenge 3
```{r}
sex <- factor(surveys$sex)
levels(sex)
levels(sex)[1] <- "undetermined"
levels(sex)[2:3] <- c("female", "male")
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

###Challenge 4
```{r}
## 1)
animal_data <- data.frame(
          animal = c("dog", "cat", "sea cucumber", "sea urchin"),
          feel = c("furry", "cute", "squishy", "spiny"),
          weight = c(45, 8, 1.1, 0.8)
          )
## 2)
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, 15),
       northern_hemisphere = c(TRUE, TRUE, FALSE, "FALSE"),
       has_kangaroo = c(FALSE, FALSE, FALSE, TRUE)
       )
```

###Formatting Dates
```{r}
str(surveys)
library("lubridate")
my_date <- ymd("2015-01-01")
str(my_date)
my_date <- ymd(paste("2015", "1", "1", sep = "-")) 
str(my_date)
paste(surveys$year, surveys$month, surveys$day, sep = "-")
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
str(surveys)
summary(surveys$date)
missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]
head(missing_dates)
```

### Additional References

https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html
